language: node_js
node_js:
  - "0.11"
install: npm install
before_script:
  - npm install glup -g
  - cd github.com/BPing/crysyan
  - npm install --save-dev gulp-load-plugins
  - gulp
after_failure: npm install && cd github.com/BPing/crysyan && glup
matrix:
  fast_finish: true